### ISSUE TITLE
Generated plugin tests failing

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1003]
when creating a new plugin, the generated unit test is failing by default.

One problem is the [seed name extension](https://github.com/webgme/webgme/blob/master/src/plugin/coreplugins/PluginGenerator/Templates/unit_test.js.ejs#L31) but I think there is something else that also needs to be updated as I am still getting the following error:
```
2016-05-24T17:23:25.096Z - error: [gme:test:CreateExecution:PluginManagerBase] TypeError: Cannot read property 'relid' of undefined
    at CoreTree.getPath (/Users/brian.broll/projects/dfst/deepforge/node_modules/webgme/src/common/core/coretree.js:361:24)
    at sameNode (/Users/brian.broll/projects/dfst/deepforge/node_modules/webgme/src/common/core/metacore.js:33:46)
    at isTypeOf (/Users/brian.broll/projects/dfst/deepforge/node_modules/webgme/src/common/core/metacore.js:205:21)
    at isTypeOf (/Users/brian.broll/projects/dfst/deepforge/node_modules/webgme/src/common/core/mixincore.js:230:27)
    at CoreQ.isTypeOf (/Users/brian.broll/projects/dfst/deepforge/node_modules/webgme/src/common/core/mixincore.js:279:20)
```

**Comment by brollb** [comment]
I think the other error is just the node id...
