### ISSUE TITLE
postinstall fails

### ISSUE THREAD

**Issue by rbanalagay** [webgme/webgme#1081]
```
> webgme@2.2.1 postinstall /usr/lib/node_modules/deepforge/node_modules/webgme
> bower install && node ./utils/postinstall.js -c jsdoc_conf.json

(node:14530) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/node_modules/configstore/index.js:56
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:640:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:508:33)
    at Object.create.all.get (/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/lib/node_modules/deepforge/node_modules/webgme/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:541:32)
```

**Comment by brollb** [comment]
Similar to https://github.com/Polymer/web-component-tester/issues/168
