### ISSUE TITLE
Applying merge resolution results in ASSERT error.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1087]
Merging `b1` into `master` leads to conflicts. When selecting resolution as shown in attached png the exception below is thrown.

![resolvemerge](https://cloud.githubusercontent.com/assets/6518904/17333250/443144d2-5897-11e6-9c98-d3a18730c804.PNG)

[guest+ActivePanels_b1.webgmex.zip](https://github.com/webgme/webgme/files/397287/guest.ActivePanels_b1.webgmex.zip)
[guest+ActivePanels_master.webgmex.zip](https://github.com/webgme/webgme/files/397288/guest.ActivePanels_master.webgmex.zip)

```
2016-08-02T14:52:16.934Z - error: [gme:server:worker:simpleworker:pid_124:WorkerFunctions:merge:core:core] object
{ stack: 'Error: object\n    at __test (C:\\GIT\\webgme\\src\\common\\core\\coretree.js:288:23)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\coretree.js:303:13)\n    at CoreTree.isValidNode (C:\\GIT\\webgme\\src\\common\\core\\coretree.js:901:17)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\corerel.js:132:40)\n    at NullPointerCore.CoreRel.isValidNode (C:\\GIT\\webgme\\src\\common\\core\\corerel.js:141:17)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:302:36)\n    at isValidNode (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:378:17)\n    at GuidCore.loadChildren (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:452:25)\n    at DiffCore.GuidCore.setGuid (C:\\GIT\\webgme\\src\\common\\core\\guidcore.js:169:21)\n    at Function.<anonymous> (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1053:29)',
  node: null }
2016-08-02T14:52:16.952Z - error: [gme:server:worker:simpleworker:pid_124:WorkerFunctions:merge:core:core] coretree
{ metadata:
   { stack: 'Error: coretree\n    at test (C:\\GIT\\webgme\\src\\common\\core\\corerel.js:35:23)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\corerel.js:132:13)\n    at NullPointerCore.CoreRel.isValidNode (C:\\GIT\\webgme\\src\\common\\core\\corerel.js:141:17)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:302:36)\n    at isValidNode (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:378:17)\n    at GuidCore.loadChildren (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:452:25)\n    at DiffCore.GuidCore.setGuid (C:\\GIT\\webgme\\src\\common\\core\\guidcore.js:169:21)\n    at Function.<anonymous> (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1053:29)\n    at Object.call (C:\\GIT\\webgme\\src\\common\\core\\tasync.js:405:30)\n    at applyNodeChange (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1023:27)',
     node: null } }
2016-08-02T14:52:16.968Z - error: [gme:server:worker:simpleworker:pid_124:WorkerFunctions:merge:core] core
{ stack: 'Error: core\n    at test (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:36:23)\n    at isValidNodeThrow (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:302:13)\n    at isValidNode (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:378:17)\n    at GuidCore.loadChildren (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:452:25)\n    at DiffCore.GuidCore.setGuid (C:\\GIT\\webgme\\src\\common\\core\\guidcore.js:169:21)\n    at Function.<anonymous> (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1053:29)\n    at Object.call (C:\\GIT\\webgme\\src\\common\\core\\tasync.js:405:30)\n    at applyNodeChange (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1023:27)\n    at Function.<anonymous> (C:\\GIT\\webgme\\src\\common\\core\\corediff.js:1043:46)\n    at Object.call (C:\\GIT\\webgme\\src\\common\\core\\tasync.js:405:30)',
  node: null }
Throwing Error: ASSERT failed
    at assert (C:\GIT\webgme\src\common\util\assert.js:14:25)
    at GuidCore.loadChildren (C:\GIT\webgme\src\common\core\coretype.js:452:13)
    at DiffCore.GuidCore.setGuid (C:\GIT\webgme\src\common\core\guidcore.js:169:21)
    at Function.<anonymous> (C:\GIT\webgme\src\common\core\corediff.js:1053:29)
    at Object.call (C:\GIT\webgme\src\common\core\tasync.js:405:30)
    at applyNodeChange (C:\GIT\webgme\src\common\core\corediff.js:1023:27)
    at Function.<anonymous> (C:\GIT\webgme\src\common\core\corediff.js:1043:46)
    at Object.call (C:\GIT\webgme\src\common\core\tasync.js:405:30)
    at applyNodeChange (C:\GIT\webgme\src\common\core\corediff.js:1023:27)
    at Function.<anonymous> (C:\GIT\webgme\src\common\core\corediff.js:1043:46)
```

**Comment by kecso** [comment]
This error message is similar to the result of #1082.
Can you reproduce it? (unfortunately the common ancestor version of the branches is necessary to reproduce the issue)
Was there any 'mergeable' change as well?

**Comment by pmeijer** [comment]
[guest+ActivePanels_common.webgmex.zip](https://github.com/webgme/webgme/files/433602/guest.ActivePanels_common.webgmex.zip)
