### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1092]
```
2016-08-03T20:22:06.595Z - error: uncaughtException: Cannot read property 'warn' of undefined 
{ date: 'Wed Aug 03 2016 15:22:06 GMT-0500 (CDT)',
  process: 
   { pid: 10420,
     uid: 502,
     gid: 20,
     cwd: '/Users/brian.broll/projects/dfst/deepforge',
     execPath: '/Users/brian.broll/.nvm/versions/node/v6.2.0/bin/node',
     version: 'v6.2.0',
     argv: 
      [ '/Users/brian.broll/.nvm/versions/node/v6.2.0/bin/node',
        '/Users/brian.broll/projects/dfst/deepforge/app.js' ],
     memoryUsage: { rss: 138649600, heapTotal: 108204032, heapUsed: 60871400 } },
  os: 
   { loadavg: [ 3.15380859375, 2.52880859375, 2.4697265625 ],
     uptime: 108455 },
  trace: 
   [ { column: 19,
       file: '/Users/brian.broll/projects/webgme/src/utils.js',
       function: null,
       line: 114,
       method: null,
       native: false },
     { column: 22,
       file: '/Users/brian.broll/projects/webgme/node_modules/express/lib/response.js',
       function: null,
       line: 412,
       method: null,
       native: false },
     { column: 5,
       file: '/Users/brian.broll/projects/webgme/node_modules/express/lib/response.js',
       function: 'SendStream.onerror',
       line: 993,
       method: 'onerror',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'SendStream.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 17,
       file: '/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js',
       function: 'SendStream.error',
       line: 245,
       method: 'error',
       native: false },
     { column: 12,
       file: '/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js',
       function: 'SendStream.onStatError',
       line: 356,
       method: 'onStatError',
       native: false },
     { column: 26,
       file: '/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js',
       function: 'onstat',
       line: 621,
       method: null,
       native: false },
     { column: 15,
       file: 'fs.js',
       function: 'FSReqWrap.oncomplete',
       line: 117,
       method: 'oncomplete',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'warn\' of undefined',
     '    at /Users/brian.broll/projects/webgme/src/utils.js:114:19',
     '    at /Users/brian.broll/projects/webgme/node_modules/express/lib/response.js:412:22',
     '    at SendStream.onerror (/Users/brian.broll/projects/webgme/node_modules/express/lib/response.js:993:5)',
     '    at emitOne (events.js:96:13)',
     '    at SendStream.emit (events.js:188:7)',
     '    at SendStream.error (/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js:245:17)',
     '    at SendStream.onStatError (/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js:356:12)',
     '    at onstat (/Users/brian.broll/projects/webgme/node_modules/express/node_modules/send/index.js:621:26)',
     '    at FSReqWrap.oncomplete (fs.js:117:15)' ] }
2016-08-03T20:22:06.606Z - error: uncaughtException: Cannot read property 'warn' of undefined 
```

**Comment by pmeijer** [comment]
Closed by #1097
