### ISSUE TITLE
Uncaught exception on executor

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1110]
```
    at finish (/Users/brian.broll/projects/webgme/src/server/worker/workerrequests.js:118:56)
    at ._callback (/Users/brian.broll/projects/webgme/src/plugin/managerbase.js:232:21)
    at save.then (/Users/brian.broll/projects/dfst/deepforge/src/plugins/ExecutePipeline/ExecutePipeline.js:364:22)
    at _fulfilled (/Users/brian.broll/projects/webgme/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/brian.broll/projects/webgme/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/brian.broll/projects/webgme/node_modules/q/q.js:796:13)
    at /Users/brian.broll/projects/webgme/node_modules/q/q.js:604:44
    at runSingle (/Users/brian.broll/projects/webgme/node_modules/q/q.js:137:13)
    at flush (/Users/brian.broll/projects/webgme/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
/Users/brian.broll/projects/webgme/src/server/middleware/executor/worker/node_worker.classes.build.js:5156
            for (i = 0; i < results.length; i += 1) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /Users/brian.broll/projects/webgme/src/server/middleware/executor/worker/node_worker.classes.build.js:5156:36
    at /Users/brian.broll/projects/webgme/src/server/middleware/executor/worker/node_worker.classes.build.js:4772:17
    at FSReqWrap.oncomplete (fs.js:117:15)
2016-08-17T15:55:54.114Z - warn: [gme:server:standalone:middleware:ExecutorServer] Did not remove all output for job 50 
{ metadata: 
   { hash: '480dc96defeec9d2bfb08bc5423b94ae11b1455a',
     resultHashes: 
      { trainingData: 'b908958c478e7d044f7883bd698d6504d4a8252a',
        testingData: '5f9b2ce27f5f80fc562e0a8f78791422aca67eb5',
        stdout: 'f4b839be8c3ad0bc5c72cbd8cfb58b16d63708a1',
        'DownloadCIFAR10-all-files': '9e72dfe0c2ed6b09767bde10c75135c73d541580' },
     resultSuperSet: null,
     userId: [],
     status: 'FAILED_TO_EXECUTE',
     createTime: '2016-08-17T15:53:39.963Z',
     startTime: '2016-08-17T15:54:50.622Z',
     finishTime: '2016-08-17T15:54:53.764Z',
     worker: 'bbroll_97223',
     labels: [],
     outputNumber: 47,
     secret: 'd8add083-bde3-5ed8-82fe-dcb88268f46b' } }

```

**Comment by brollb** [comment]
I think this happens if the worker dir is deleted while the job is running
