### ISSUE TITLE
autoMerge fails: Maximum call stack exceeded

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1117]
autoMerge has been failing in my plugin when I have multiple instances (probably about 4 or so) of a plugin running (all committing back to the same branch):
```
2016-08-18T20:02:02.376Z - info: [gme:server:standalone:WebSocket] Merge successful 
{ status: 'FORKED',
  hash: '#8a90717bdc43a57a740bf836ede8ef187de3a904' }
2016-08-18T20:02:03.437Z - error: [gme:server:worker:simpleworker:pid_70406:WorkerFunctions] autoMerge [guest+merging] failed with error RangeError: Maximum call stack size exceeded
    at target.(anonymous function) (/Users/brian.broll/projects/webgme/node_modules/winston/lib/winston/common.js:53:55)
    at Logger.debug (/Users/brian.broll/projects/webgme/src/server/logger.js:130:26)
    at ProjectCache.loadObject (/Users/brian.broll/projects/webgme/src/common/storage/project/cache.js:71:20)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
    at Project.func.tasync_wraped (/Users/brian.broll/projects/webgme/src/common/core/tasync.js:476:22)
2016-08-18T20:02:03.455Z - error: [gme:server:standalone:WebSocket] Merging failed Maximum call stack size exceeded
```

**Comment by kecso** [comment]
please clarify if this was a result of faulty code in the plugin or not (as the latest version of deepforge doesn't has this issue anymore)

**Comment by brollb** [comment]
I can check it out tonight

**Comment by brollb** [comment]
I haven't seen this since so I am going to suppose it is no longer an issue
