### ISSUE TITLE
getAttribute from rootNode fails

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1131]
Calling `this.core.getAttribute(this.rootNode, 'version')` fails on the root node:
```
2016-08-28T23:01:25.482Z - error: [gme:server:worker:simpleworker:pid_9845:WorkerFunctions:PluginManagerBase] RangeError: Maximum call stack size exceeded
    at isValidNode (/home/irishninja/projects/webgme/src/common/core/coretype.js:381:58)
    at CoreQ.getAttribute (/home/irishninja/projects/webgme/src/common/core/coretype.js:648:25)
    at UpdateLibrarySeed.getVersion (/home/irishninja/projects/dfst/deepforge/src/plugins/UpdateLibrarySeed/UpdateLibrarySeed.js:94:30)
    at PluginBase.save (/home/irishninja/projects/webgme/src/plugin/PluginBase.js:423:73)
    at UpdateLibrarySeed.getVersion (/home/irishninja/projects/dfst/deepforge/src/plugins/UpdateLibrarySeed/UpdateLibrarySeed.js:100:21)
    at PluginBase.save (/home/irishninja/projects/webgme/src/plugin/PluginBase.js:423:73)
    at UpdateLibrarySeed.getVersion (/home/irishninja/projects/dfst/deepforge/src/plugins/UpdateLibrarySeed/UpdateLibrarySeed.js:100:21)
    at PluginBase.save (/home/irishninja/projects/webgme/src/plugin/PluginBase.js:423:73)
    at UpdateLibrarySeed.getVersion (/home/irishninja/projects/dfst/deepforge/src/plugins/UpdateLibrarySeed/UpdateLibrarySeed.js:100:21)
    at PluginBase.save (/home/irishninja/projects/webgme/src/plugin/PluginBase.js:423:73)

```

**Comment by kecso** [comment]
It was a faulty plugin implementation (infinite loop among functions of the plugin)
