### ISSUE TITLE
Error: tried to insert existing hash - the two objects were NOT equal

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1218]
Getting the following error when running a plugin:
```
2016-10-18T01:26:55.850Z - error: [gme:server:worker:simpleworker:pid_5051:WorkerFunctions] plugin [ExecutePipeline] failed with error Error: Operation "/K/g/0/b" failed! {"hash":"a68cd90b43e9a3562a431828860d4eaadc56f96d","resultHashes":{"net":"0aa103fbd3b22ab1f5b39f75e6a1ba24c89b0357","stdout":"8bca6cde62795dbc4de1702b8c3eb57e34acb006","train-all-files":"6410d7213a1417a97ca3ee217cbea7d2fc608ef1"},"resultSuperSet":null,"userId":[],"status":"FAILED_TO_EXECUTE","createTime":"2016-10-18T01:26:52.575Z","startTime":"2016-10-18T01:26:54.994Z","finishTime":"2016-10-18T01:26:55.346Z","worker":"mjolnir_5099","labels":[],"outputNumber":0}
    at finish (/home/irishninja/projects/dfst/deepforge/node_modules/webgme/src/server/worker/workerrequests.js:129:56)
    at ._callback (/home/irishninja/projects/dfst/deepforge/node_modules/webgme/src/plugin/managerbase.js:232:21)
    at save.then (/home/irishninja/projects/dfst/deepforge/src/plugins/ExecutePipeline/ExecutePipeline.js:368:30)
    at _fulfilled (/home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:796:13)
    at /home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:604:44
    at runSingle (/home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:137:13)
    at flush (/home/irishninja/projects/dfst/deepforge/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-10-19T01:04:12.438Z - error: [gme:server:standalone:mongo] tried to insert existing hash - the two objects were NOT equal  newObject=["Object","_hasownrelation",true,"_id","#9d6a2246bc23c75ad03067afeac7dd962678eed8","atr",["Object"]], oldObject=["Object","_hasownrelation",true,"_id","#9d6a2246bc23c75ad03067afeac7dd962678eed8"]
2016-10-19T01:04:12.443Z - error: [gme:server:worker:simpleworker:pid_22544:WorkerFunctions:PluginManagerBase:plugin:ExecutePipeline] Error: tried to insert existing hash - the two objects were NOT equal #9d6a2246bc23c75ad03067afeac7dd962678eed8
2016-10-19T01:04:12.440Z - error: [gme:server:standalone:storage] Error: tried to insert existing hash - the two objects were NOT equal #9d6a2246bc23c75ad03067afeac7dd962678eed8
2016-10-19T03:38:15.764Z - error: [gme:server:standalone:mongo] tried to insert existing hash - the two objects were NOT equal  newObject=["Object","_hasownrelation",true,"_id","#9d6a2246bc23c75ad03067afeac7dd962678eed8","atr",["Object"]], oldObject=["Object","_hasownrelation",true,"_id","#9d6a2246bc23c75ad03067afeac7dd962678eed8"]
2016-10-19T03:38:15.769Z - error: [gme:server:standalone:storage] Error: tried to insert existing hash - the two objects were NOT equal #9d6a2246bc23c75ad03067afeac7dd962678eed8
2016-10-19T03:38:15.771Z - error: [gme:server:worker:simpleworker:pid_22762:WorkerFunctions:PluginManagerBase:plugin:ExecutePipeline] Error: tried to insert existing hash - the two objects were NOT equal #9d6a2246bc23c75ad03067afeac7dd962678eed8
```

**Comment by kecso** [comment]
The steps leading to the issue are the followings:
- the persist doesn't clean up an empty 'atr' object
- the json patcher doesn't generate any change operation between the following two objects:
obj1 = { _id: 'c91ed7b9d062ca0947c4cc7fb3ca03412e5edc01',
  _hasownrelation: true }
vs
obj2 = { _id: '9d6a2246bc23c75ad03067afeac7dd962678eed8',
  _hasownrelation: true,
  atr: {} }
- given the following scenario:
 -1 obj1 inserted to DB
 -2 ojb1 inserted to DB under hash2 (due to faulty patch) as well
-3 obj2 is created (by making an instance, setting a pointer, then add and removing an attribute within the same transaction) -> obj2 cannot be inserted as the hash is already reserved

The solution is to eliminate the empty object during persist.
