### ISSUE TITLE
Uncaught exception at noMoreCommitsToDisplay in ProjectRepositoryWidget

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1288]
Details:
https://sentry.io/vanderbilt-university/webgme/issues/203613797/

```
TypeError: Cannot read property 'empty' of undefined
  at _noMoreCommitsToDisplay(client/js/Widgets/ProjectRepository/ProjectRepositoryWidget.js:979:0)
  at noMoreCommitsToDisplay(client/js/Widgets/ProjectRepository/ProjectRepositoryWidget.js:182:0)
  at apply(client/js/Widgets/ProjectRepository/ProjectRepositoryWidgetControl.js:37:0)
  at apply(common/storage/socketio/websocket.js:34:0)
  at Socket.onack(/socket.io/socket.io.js:985:9)
  at Socket.onpacket(/socket.io/socket.io.js:909:12)
  at Manager.<anonymous>(/socket.io/socket.io.js:1512:15)
  at Manager.Emitter.emit(/socket.io/socket.io.js:1647:20)
  at Manager.ondecoded(/socket.io/socket.io.js:428:8)
  at Decoder.<anonymous>(/socket.io/socket.io.js:1512:15)
  at Decoder.Emitter.emit(/socket.io/socket.io.js:4389:20)
  at Decoder.add(/socket.io/socket.io.js:6740:12)
  at Manager.ondata(/socket.io/socket.io.js:418:16)
  at Socket.<anonymous>(/socket.io/socket.io.js:1512:15)
  at Socket.Emitter.emit(/socket.io/socket.io.js:4389:20)
  at Socket.onPacket(/socket.io/socket.io.js:2514:14)
  at WS.<anonymous>(/socket.io/socket.io.js:2331:10)
  at WS.Emitter.emit(/socket.io/socket.io.js:4389:20)
  at WS.Transport.onPacket(/socket.io/socket.io.js:2947:8)
  at WS.Transport.onData(/socket.io/socket.io.js:2939:8)
  at WebSocket.ws.onmessage(/socket.io/socket.io.js:4058:10)
```

**Comment by pmeijer** [comment]
https://sentry.io/vanderbilt-university/webgme/issues/203613797/
