### ISSUE TITLE
Uncaught exception in ConnectionRouteManager3

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1289]
https://sentry.io/vanderbilt-university/webgme/issues/202968580/

```
TypeError: s is undefined
  at this(client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js:535:0)
  at this(client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js:144:0)
```

This stack-trace is misleading.. The AutoRouterActionApplier is treated as a lib with no source map.

**Comment by pmeijer** [comment]
Closed by #1293
