### ISSUE TITLE
Load timeout for jquery-fancytree

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1291]
https://sentry.io/vanderbilt-university/webgme/issues/203406159/

```
Error: Load timeout for modules: jquery-fancytree
http://requirejs.org/docs/errors.html#timeout
  at C (/lib/require/require.min.js:8:252)
  at D (/lib/require/require.min.js:13:480)
  at ha/D/Y< (/lib/require/require.min.js:14:133)
  at i (/dist/webgme.lib.build.js:22:20408)
```

**Comment by pmeijer** [comment]
https://sentry.io/vanderbilt-university/webgme/issues/199718443/
