### ISSUE TITLE
Client exception related to notifications and user interaction

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1355]
I've found that when I click on the notifications button when notifications are popping up, if the notification bubble is above the button then an exception will be triggered.

**Comment by finger563** [comment]
![pasted image at 2017_03_29 10_25 am](https://cloud.githubusercontent.com/assets/213467/24620267/98a5932a-1862-11e7-89ea-ce7167d9689d.png)

**Comment by finger563** [comment]
```
{
  "timestamp": "2017-04-03T16:51:24.738Z",
  "webgme": {
    "NpmVersion": "2.11.1",
    "version": "2.11.1",
    "GitHubVersion": "webgme@>=2.0.0 <3.0.0"
  },
  "gmeConfig": {
    "addOn": {
      "enable": false,
      "monitorTimeout": 10000,
      "basePaths": [
        "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/addon/core"
      ]
    },
    "authentication": {
      "enable": true,
      "allowGuests": true,
      "allowUserRegistration": true,
      "guestAccount": "guest",
      "logOutUrl": "/profile/login",
      "logInUrl": "/profile/login",
      "jwt": {
        "cookieId": "access_token",
        "tokenGenerator": "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/server/middleware/auth/localtokengenerator.js",
        "algorithm": "RS256"
      }
    },
    "client": {
      "appDir": "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/client",
      "log": {
        "level": "debug"
      },
      "defaultConnectionRouter": "basic3",
      "errorReporting": {
        "enable": false,
        "DSN": "",
        "ravenOptions": null
      }
    },
    "core": {
      "enableCustomConstraints": true,
      "inverseRelationsCacheSize": 2000,
      "overlayShardSize": 10000
    },
    "debug": false,
    "executor": {
      "enable": true,
      "workerRefreshInterval": 5000,
      "clearOutputTimeout": 60000,
      "clearOldDataAtStartUp": false,
      "labelJobs": "./labelJobs.json"
    },
    "plugin": {
      "allowBrowserExecution": true,
      "allowServerExecution": true,
      "basePaths": [
        "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/plugin/coreplugins",
        "/home/jeb/repositories/webgme-rosmod/config/../src/plugins"
      ],
      "displayAll": false,
      "serverResultTimeout": 60000
    },
    "requirejsPaths": {
      "panels": "/extlib/./src/visualizers/panels",
      "widgets": "/extlib/./src/visualizers/widgets",
      "panels/CodeEditor": "/extlib/./node_modules/webgme-codeeditor/src/visualizers/panels/CodeEditor",
      "widgets/CodeEditor": "/extlib/./node_modules/webgme-codeeditor/src/visualizers/widgets/CodeEditor",
      "panels/FloatingActionButton": "/extlib/./node_modules/webgme-fab/src/visualizers/panels/FloatingActionButton",
      "widgets/FloatingActionButton": "/extlib/./node_modules/webgme-fab/src/visualizers/widgets/FloatingActionButton",
      "panels/BreadcrumbHeader": "/extlib/./node_modules/webgme-breadcrumbheader/src/visualizers/panels/BreadcrumbHeader",
      "widgets/BreadcrumbHeader": "/extlib/./node_modules/webgme-breadcrumbheader/",
      "rosmod": "/extlib/./src/common/",
      "cytoscape": "/extlib/./node_modules/cytoscape/dist",
      "plottable": "/extlib/./node_modules/plottable/",
      "handlebars": "/extlib/./node_modules/handlebars/",
      "cytoscape-cose-bilkent": "/extlib/./node_modules/cytoscape-cose-bilkent/",
      "webgme-to-json": "/extlib/./node_modules/webgme-to-json/",
      "remote-utils": "/extlib/./node_modules/remote-utils/",
      "plotly-js": "/extlib/./node_modules/plotly.js/dist/"
    },
    "seedProjects": {
      "enable": true,
      "allowDuplication": true,
      "defaultProject": "EmptyProject",
      "basePaths": [
        "./src/seeds"
      ]
    },
    "socketIO": {
      "clientOptions": {
        "reconnection": true,
        "connect timeout": 10,
        "reconnection delay": 1,
        "force new connection": true,
        "path": "/socket.io",
        "hostname": "192.168.202.128",
        "secure": false,
        "port": "8080"
      }
    },
    "storage": {
      "cache": 2000,
      "broadcastProjectEvents": false,
      "maxEmittedCoreObjects": -1,
      "loadBucketSize": 100,
      "loadBucketTimer": 10,
      "clientCacheSize": 2000,
      "autoMerge": {
        "enable": false
      },
      "keyType": "plainSHA1",
      "disableHashChecks": false,
      "requireHashesToMatch": true
    },
    "visualization": {
      "extraCss": [],
      "decoratorPaths": [
        "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/client/decorators",
        "/home/jeb/repositories/webgme-rosmod/config/../src/decorators"
      ],
      "decoratorsToPreload": null,
      "svgDirs": [
        "./src/svgs"
      ],
      "visualizerDescriptors": [
        "./src/visualizers/Visualizers-dev.json"
      ],
      "panelPaths": [
        "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/client/js/Panels",
        "/home/jeb/repositories/webgme-rosmod/config/../node_modules/webgme-breadcrumbheader/src/visualizers/panels",
        "/home/jeb/repositories/webgme-rosmod/config/../node_modules/webgme-fab/src/visualizers/panels",
        "/home/jeb/repositories/webgme-rosmod/config/../node_modules/webgme-codeeditor/src/visualizers/panels",
        "/home/jeb/repositories/webgme-rosmod/config/../src/visualizers/panels",
        "./src/visualizers/panels"
      ],
      "layout": {
        "basePaths": [
          "/home/jeb/repositories/webgme-rosmod/node_modules/webgme/src/client/js/Layouts",
          "/home/jeb/repositories/webgme-rosmod/config/../src/layouts",
          "./src/layouts"
        ],
        "default": "NewDefaultLayout"
      }
    },
    "webhooks": {
      "enable": false,
      "manager": "memory"
    },
    "server": {
      "port": 8080
    }
  },
  "uiState": {
    "activeAspect": "All",
    "layout": "NewDefaultLayout",
    "activeVisualizer": "ModelEditor",
    "activeProjectName": "guest+rosmod",
    "activeBranchName": "master",
    "activeCommit": null,
    "activeObject": "/v/0",
    "activeTab": 0
  },
  "branchErrors": [],
  "browserInfo": {
    "appCodeName": "Mozilla",
    "appName": "Netscape",
    "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
    "onLine": true,
    "cookieEnabled": true,
    "platform": "Win32",
    "product": "Gecko",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
  },
  "clientState": {
    "connection": "CONNECTED",
    "renewingToken": false,
    "exception": {
      "message": "Cannot read property 'trigger' of null",
      "stack": "TypeError: Cannot read property 'trigger' of null\n    at HTMLDivElement.g (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:13:31967)\n    at HTMLDivElement.r (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:1:3086)\n    at HTMLDivElement.handle (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:13:8708)\n    at HTMLDivElement.dispatch (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:2:16849)\n    at HTMLDivElement.g.handle (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:2:14922)\n    at Object.trigger (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:3:7186)\n    at HTMLDivElement.<anonymous> (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:3:7750)\n    at Function.each (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:1:14851)\n    at at.fn.init.each (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:1:12818)\n    at at.fn.init.trigger (http://192.168.202.128:8080/dist/webgme.2.11.1.lib.build.js:3:7725)"
    },
    "projectAccess": {
      "read": true,
      "write": true,
      "delete": true
    },
    "projectInfo": {
      "_id": "guest+rosmod",
      "owner": "guest",
      "name": "rosmod",
      "info": {
        "createdAt": "2017-03-24T16:06:49.679Z",
        "viewedAt": "2017-04-03T16:50:42.853Z",
        "modifiedAt": "2017-04-03T16:19:09.007Z",
        "creator": "guest",
        "viewer": "guest",
        "modifier": "guest",
        "kind": "samples"
      },
      "hooks": {},
      "rights": {
        "read": true,
        "write": true,
        "delete": true
      },
      "branches": {
        "master": "#286b7a15bb25b8cf70e61cfd69f3afc209fe9da3"
      }
    },
    "core": "instantiated",
    "branchName": "master",
    "branchStatus": "SYNC",
    "readOnlyProject": false,
    "viewer": false,
    "users": [
      "_part_browser_",
      "8deac8b3-08d2-8a21-2669-9974203221bd",
      "59c51487-7d56-303c-f964-0bbe922e5aa0",
      "4d64291d-3b89-54fc-3a02-9322c0009b70",
      "6635f9ef-88f0-394f-1c77-18517be5d48d",
      "beb56ae3-11c6-7b5c-8644-65895cf4e263",
      "882cdffd-8da7-0cc4-df55-95ac4ef18caa",
      "c27e5fc9-e6c8-d2d9-167e-4c4143d3f4d8",
      "debec0d8-815e-bcb8-083d-bba94364d3c4",
      "bd4ae7ac-396d-2877-538b-9ee4584a79a3",
      "91493314-39c1-e669-90c8-356bbc3b9b80",
      "c01d5885-10a1-639f-ae48-8d62e9fc88b7",
      "6977220f-fd5a-54d0-8f3c-a57a546890f4",
      "d465097f-9be6-efed-4f6f-d98f1790f3cf",
      "2b9680fa-cdcf-c0e2-25a0-926de384dbd7",
      "d0f8bad5-ba5b-27a6-74e2-c279057f0d7b"
    ],
    "nodes": [
      "",
      "/1",
      "/3",
      "/v",
      "/3/R",
      "/3/z",
      "/3/d",
      "/3/U",
      "/3/Jt",
      "/3/2",
      "/3/m",
      "/3/8",
      "/3/b",
      "/3/9",
      "/3/q",
      "/3/Z",
      "/3/W",
      "/3/w",
      "/3/j",
      "/3/P",
      "/3/n",
      "/3/5",
      "/3/I",
      "/3/e",
      "/3/L",
      "/3/x",
      "/3/h",
      "/3/r",
      "/3/s",
      "/3/1",
      "/3/K",
      "/3/F",
      "/3/f",
      "/3/a",
      "/3/V",
      "/3/c",
      "/3/l",
      "/3/i",
      "/v/0",
      "/v/0/g",
      "/v/0/R",
      "/v/0/f",
      "/v/0/s",
      "/v/0/u",
      "/v/0/g/L",
      "/v/0/g/l",
      "/v/0/f/8",
      "/v/0/f/w",
      "/v/0/f/d",
      "/v/0/f/f",
      "/v/0/f/Z",
      "/v/0/s/j",
      "/v/0/s/C",
      "/v/0/u/E",
      "/v/0/u/Q"
    ],
    "loadNodes": [],
    "rootHash": "#e0d6abe69e942e885d8dc79461858842399d562b",
    "commitHash": "#286b7a15bb25b8cf70e61cfd69f3afc209fe9da3",
    "undoRedoChain": {
      "previous": null,
      "next": null
    },
    "inTransaction": false,
    "msg": "",
    "gHash": 0,
    "loadError": null,
    "ongoingTerritoryUpdateCounter": 0,
    "ongoingLoadPatternsCounter": 0,
    "pendingTerritoryUpdatePatterns": {},
    "loadingStatus": null,
    "inLoading": false,
    "loading": {
      "rootHash": null,
      "commitHash": null
    }
  }
}
```
