### ISSUE TITLE
CoreInternalError: ASSERT failed

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1585]
https://sentry.io/vanderbilt-university/webgme/issues/503383159/

```
CoreInternalError: ASSERT failed
  at new CoreInternalError (../node_modules/webgme-engine/src/common/core/CoreInternalError.js:13:1)
  at assert (../node_modules/webgme-engine/src/common/core/CoreAssert.js:14:1)
  at SetCore.CoreType.createNode (../node_modules/webgme-engine/src/common/core/coretype.js:742:1)
  at MetaCore.GuidCore.createNode (../node_modules/webgme-engine/src/common/core/guidcore.js:125:1)
  at CoreTreeLoader.MetaCacheCore.createNode (../node_modules/webgme-engine/src/common/core/metacachecore.js:65:1)
...
(8 additional frame(s) were not displayed)
```

**Comment by arpika99** [comment]
Hello,

This issue still persists on my end.

![image](https://user-images.githubusercontent.com/55790409/144822643-0e766b37-a021-49ba-82ac-c359c59419e1.png)

Is there any workaround?

**Comment by kecso** [comment]
Could you please open a new issue, and describe the steps that lead to this error?
It appears to be a different one than the original you reported...

Thank you,
Tamas
