### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1614]
https://sentry.io/vanderbilt-university/webgme/issues/583837727/

```
TypeError: Cannot read property 'indexOf' of undefined
  at CrosscutController.DiagramDesignerWidgetMultiTabMemberListControllerBase._onBackgroundDroppableAccept (client/js/Panels/ControllerBase/DiagramDesignerWidgetMultiTabMemberListControllerBase.js:616:1)
  at CrosscutController._onBackgroundDroppableAccept (client/js/Panels/Crosscut/CrosscutController.js:286:1)
  at CrosscutWidget._widget.onBackgroundDroppableAccept (client/js/Panels/ControllerBase/DiagramDesignerWidgetMultiTabMemberListControllerBase.js:98:1)
  at CrosscutWidget.DiagramDesignerWidgetDroppable._onDroppableOver (client/js/Widgets/DiagramDesigner/DiagramDesignerWidget.Droppable.js:75:1)
  at ae.fn.init.over (client/js/Widgets/DiagramDesigner/DiagramDesignerWidget.Droppable.js:30:1)
...
(16 additional frame(s) were not displayed)
```

**Comment by pmeijer** [comment]
Fixed by #1617
