### ISSUE TITLE
Error when merging branch (Cannot read property 'oBaseGuids')

### ISSUE THREAD

**Issue by chrisfrederickson** [webgme/webgme#1678]
When attempting to merge a branch, I get the error message `Error: Cannot read property of 'oBaseGuids' of null` shown below.

![webgme_merge_error](https://user-images.githubusercontent.com/3927363/56053656-ae890f80-5d22-11e9-8ca4-08dfb6908446.PNG)

The closest issues that I can find are #1033 and #1082. When creating a new project, merging works fine, so something in the project I am working on is to blame. Unfortunately, I cannot share the project but will attempt to create a minimal working example of the problem that can be shared.

Does anyone have any insights as to what is most likely to blame in the mean time?

**Comment by kecso** [comment]
Yeah, that is weird indeed.
Could you please try to get the full error trace? (that could point us closer to the source)
It seems like one of the diffs are just completely empty and somehow the system still not using the 'fast-forward' but try to actually merge.

**Comment by chrisfrederickson** [comment]
Here is the error trace.

```
2019-04-19T17:50:44.691Z - error: [gme:server:worker:simpleworker:pid_28:WorkerFunctions] autoMerge [Insituware+REMOVED] failed with error
{ message: 'Cannot read property \'oBaseGuids\' of null',
  stack:
   'TypeError: Cannot read property \'oBaseGuids\' of null
   at checkContainer (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:949:59)
   at checkContainer (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:970:32)
   at fixInheritanceCollision (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:978:21)
   at fixInheritanceCollision (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:1004:17)
   at fixInheritanceCollision (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:1004:17)
   at fixInheritanceCollision (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:1004:17)
   at fixInheritanceCollision (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:1004:17)
   at Object.DiffCore.tryToConcatChanges (/usr/app/node_modules/webgme-engine/src/common/core/corediff.js:2722:13)
   at CoreQ.Core.tryToConcatChanges (/usr/app/node_modules/webgme-engine/src/common/core/core.js:3319:25)
   at /usr/app/node_modules/webgme-engine/src/common/core/users/merge.js:285:44' 
}
```

When I create a new branch from our master branch, make a few changes, and merge it back into master, everything seems to work now. For a short period of time, it was still broken on a branch that I had made to test this previously (which is how I got the above error trace), but now I can't seem to reproduce the issue.

**Comment by kecso** [comment]
It seems that some node in the branch you try to merge got corrupted somehow. 
I will keep the issue open and check back if anything can be done.
Maybe if you have the history of the branch, then we can figure out a modification that might caused this in the first place.
