### ISSUE TITLE
Server crashes when trying to switch to non-existing branch

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#171]
~~~~
Throwing Error: ASSERT failed
    at assert (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/util/assert.js:12:16)
    at Object.getBranchHash (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/mongo.js:316:9)
    at Object.getBranchHash (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/cache.js:263:14)
    at Object.getBranchHash (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/log.js:137:13)
    at /Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/server.js:586:37
    at /Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/log.js:68:6
    at Object.reopenProject (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/cache.js:305:5)
    at /Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/cache.js:44:21
    at Object.lock (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/cache.js:17:6)
    at Object.openProject (/Users/laszlojuracz/Projects/morph/mms-webcyphy/node_modules/webgme/src/common/storage/cache.js:42:10)

Error have been raised on socket.io level!!! -  [Error: ASSERT failed]
~~~~

**Comment by nabana** [comment]
Can you bump the priority of this?

I spend some time debugging where my app gets lost and it ended up finding this issue again today.

Thanks

**Comment by lattmann** [comment]
Cannot reproduce with master branch 2e64fb0d369781c691ba740eb008ef6a2a0af4c5
