### ISSUE TITLE
Module can not be found

### ISSUE THREAD

**Issue by magyariE** [webgme/webgme#1715]
Hello, 

I have created a plugin with the command: 

webgme new plugin ResultGenerator --language Python

In the directory of the project:

/home/endre/SDx

The problem is that when I am trying to run this interpreter the server tries to locate one directory lower:

2020-11-16T12:01:56.462Z - error: [gme:server:worker:simpleworker:pid_385:WorkerFunctions] plugin [ResultGenerator] failed with error message=Tried loading "plugin/ResultGenerator/ResultGenerator/ResultGenerator" at /home/endre/SDx/node_modules/webgme-engine/src/plugin/ResultGenerator/ResultGenerator/ResultGenerator.js then tried node's require("plugin/ResultGenerator/ResultGenerator/ResultGenerator") and it failed with error: Error: Cannot find module 'plugin/ResultGenerator/ResultGenerator/ResultGenerator', stack=Error: Tried loading "plugin/ResultGenerator/ResultGenerator/ResultGenerator" at /home/endre/SDx/node_modules/webgme-engine/src/plugin/ResultGenerator/ResultGenerator/ResultGenerator.js then tried node's require("plugin/ResultGenerator/ResultGenerator/ResultGenerator") and it failed with error: Error: Cannot find module 'plugin/ResultGenerator/ResultGenerator/ResultGenerator'

[endre@webgme SDx]$ pwd
/home/endre/SDx
[endre@webgme SDx]$ ls -laR src/plugins/ResultGenerator/ 
src/plugins/ResultGenerator/:
total 20
drwxrwxr-x. 3 endre endre  117 Nov 16 12:11 .
drwxrwxr-x. 6 endre endre   96 Nov 16 12:11 ..
drwxrwxr-x. 2 endre endre   25 Nov 16 14:01 ResultGenerator
-rw-rw-r--. 1 endre endre 5057 Nov 16 12:11 ResultGenerator.js
-rw-rw-r--. 1 endre endre  329 Nov 16 12:11 metadata.json
-rw-rw-r--. 1 endre endre 2048 Nov 16 12:11 run_debug.py
-rw-rw-r--. 1 endre endre 1714 Nov 16 12:11 run_plugin.py

src/plugins/ResultGenerator/ResultGenerator:
total 8
drwxrwxr-x. 2 endre endre   25 Nov 16 14:01 .
drwxrwxr-x. 3 endre endre  117 Nov 16 12:11 ..
-rw-rw-r--. 1 endre endre 5045 Nov 16 14:01 __init__.py
[endre@webgme SDx]$ 

ANy though how can we recover from this situation and fix for further plugins?

Regards
Endre

**Comment by kecso** [comment]
I know it looks weird, but that is how it should normally.
How were you trying to run the plugin?

all the configuration you need should be in the config.webgme.js (config.plugin.basePaths.push(__dirname + '/../src/plugins');)

**Comment by magyariE** [comment]
Hello Tamás, 

I was running it from a web browser. 

Weird is that I have a different interpreter which is working. 


Error log:

2020-11-16T12:02:59.017Z - error: [gme:server:worker:simpleworker:pid_385:WorkerFunctions] plugin [ResultGenerator] failed with error message=Tried loading "plugin/ResultGenerator/ResultGenerator/ResultGenerator" at /home/endre/SDx/node_modules/webgme-engine/src/plugin/ResultGenerator/ResultGenerator/ResultGenerator.js then tried node's require("plugin/ResultGenerator/ResultGenerator/ResultGenerator") and it failed with error: Error: Cannot find module 'plugin/ResultGenerator/ResultGenerator/ResultGenerator', stack=Error: Tried loading "plugin/ResultGenerator/ResultGenerator/ResultGenerator" at /home/endre/SDx/node_modules/webgme-engine/src/plugin/ResultGenerator/ResultGenerator/ResultGenerator.js then tried node's require("plugin/ResultGenerator/ResultGenerator/ResultGenerator") and it failed with error: Error: Cannot find module 'plugin/ResultGenerator/ResultGenerator/ResultGenerator'
    at /home/endre/SDx/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/home/endre/SDx/node_modules/requirejs/bin/r.js:1946:33)
    at Module.check (/home/endre/SDx/node_modules/requirejs/bin/r.js:1128:55)
    at Module.enable (/home/endre/SDx/node_modules/requirejs/bin/r.js:1426:22)
    at Module.init (/home/endre/SDx/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/home/endre/SDx/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/home/endre/SDx/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/home/endre/SDx/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/home/endre/SDx/node_modules/requirejs/bin/r.js:1935:21)
    at Module.load (/home/endre/SDx/node_modules/requirejs/bin/r.js:1084:29), code=MODULE_NOT_FOUND, moduleName=plugin/ResultGenerator/ResultGenerator/ResultGenerator, requireModules=[plugin/ResultGenerator/ResultGenerator/ResultGenerator], prefix=undefined, name=plugin/ResultGenerator/ResultGenerator/ResultGenerator, parentMap=undefined, unnormalized=false, url=/home/endre/SDx/node_modules/webgme-engine/src/plugin/ResultGenerator/ResultGenerator/ResultGenerator.js, originalName=plugin/ResultGenerator/ResultGenerator/ResultGenerator, isDefine=true, id=plugin/ResultGenerator/ResultGenerator/ResultGenerator, requireType=define


config/config.webgme.js
// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');





config.rest.components['BindingsDocs'] = {
  src: __dirname + '/../node_modules/webgme-bindings/src/routers/BindingsDocs/BindingsDocs.js',
  mount: 'bindings-docs',
  options: {}
};

// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'BindingsDocs': 'node_modules/webgme-bindings/src/routers/BindingsDocs',
  'webgme-bindings': './node_modules/webgme-bindings/src/common',
  'sdx': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/sdx';
validateConfig(config);
module.exports = config;



[endre@webgme SDx]$ ls -la src/plugins/
total 0
drwxrwxr-x. 6 endre endre  96 Nov 16 12:11 .
drwxrwxr-x. 5 endre endre  54 Jun  5 00:19 ..
drwxrwxr-x. 3 endre endre  95 Sep 23 14:54 GD_1
drwxrwxr-x. 3 endre endre 117 Nov 16 12:11 SDxJsonExport
drwxrwxr-x. 3 endre endre 113 Jun  5 09:47 SDxJsonExport
drwxrwxr-x. 2 endre endre  64 Jun  5 09:45 SDxJsonGeneratorClientSide
[endre@webgme SDx]$ 



Here SDxJsonExport is working and SDxJsonExport gives the above error. 


Many thanks!
Endre

**Comment by kecso** [comment]
That is odd.
What I would try is to save the code and generate it once again.
Then try to execute without any modifications, if that works, then it is something in your code.

I tried to replicate it by adding errors to the js file, but that resulted in a different error.
What I can confirm is that the plugin\pluginName\pluginName\pluginName path is the correct one...
