### ISSUE TITLE
core.add_member causing exception

### ISSUE THREAD

**Issue by magyariE** [webgme/webgme#1737]
Hello, 

During running of a plugin, **core.add_member (node,member)** throws the below exception: 
Seems to me that it is related to the volume of manipulations of the objects. 

If I split the number of operations in two runs of the same interpreter, it does not happen anymore. 

Do you have any idea what could cause this?

Thanks:
Endre

 File "/home/endre/CSOSync/src/plugins/AddressImporter/AddressImporter/__init__.py", line 262, in main
    core.add_member(group_o, "Adresses", address_o)
  File "/home/endre/.local/lib/python3.6/site-packages/webgme_bindings/core.py", line 79, in add_member
    return self._send({'name': 'addMember', 'args': [node, name, member]})
  File "/home/endre/.local/lib/python3.6/site-packages/webgme_bindings/core.py", line 25, in _send
    return self._webgme.handle_response()
  File "/home/endre/.local/lib/python3.6/site-packages/webgme_bindings/webgme.py", line 89, in handle_response
    raise JSError(res['err'])
webgme_bindings.exceptions.JSError: Cannot read property 'itemCount' of undefined

2021-09-22T08:40:39.646Z - error: [gme:server:worker:simpleworker:pid_4619:WorkerFunctions:PluginManagerBase:plugin:AddressImporter] Error: python /home/endre/CSOSync/src/plugins/AddressImporter/run_plugin.py 5555 "#cbe64c3243aed3d67a171203610ad9b108ed1028" "master" "/w" "" "LiteSO" exited with code 1.
    at ChildProcess.childProc.on (/home/endre/CSOSync/src/plugins/AddressImporter/AddressImporter.js:99:37)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2021-09-22T08:40:39.647Z - error: [gme:server:worker:simpleworker:pid_4619:WorkerFunctions] plugin [AddressImporter] failed with error message=python /home/endre/CSOSync/src/plugins/AddressImporter/run_plugin.py 5555 "#cbe64c3243aed3d67a171203610ad9b108ed1028" "master" "/w" "" "LiteSO" exited with code 1., stack=Error: python /home/endre/CSOSync/src/plugins/AddressImporter/run_
plugin.py 5555 "#cbe64c3243aed3d67a171203610ad9b108ed1028" "master" "/w" "" "LiteSO" exited with code 1.
    at ChildProcess.childProc.on (/home/endre/CSOSync/src/plugins/AddressImporter/AddressImporter.js:99:37)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by kecso** [comment]
Well, the error points to a sharding method that tries to ensure relations among nodes (that has to be stored in their common container) are kept in balance.
Most probably this is an error on our end.
Could you give me a short description of the things you are trying to do in a single commit? (a ballpark number of the number of member creation)
Once I check it out it can probably be stabilized by some of our configurations, but I have to make sure beforehand, that we know what the actual issue is.

**Comment by magyariE** [comment]
Hi Tamás, 


Thank you for looking into this. 

well i was creating like ~ 5000 objects and then I was creating different member associations between them, there could be member pointers with > 200 member objects. 

If I split my data into two parts and run the intrepreter on the same dataset in two sessions, there were no issues. 

I also tried to do commits so that not all the changes between the same plugin session would be in the same commit but that did not help. 


Thanks:
Endre

**Comment by magyariE** [comment]
Is there a root cause identified on this one yet ?
Would you need any more debugging info ?

**Comment by kecso** [comment]
Unfortunately, I am yet to reproduce the issue (my initial tries have not succeeded).
The information is adequate (at this point).
I will probably have time to give it another go today or tomorrow...

**Comment by magyariE** [comment]
It is not related to a volume of add_member. I narrowed this down to a single add_member operation and performed from the UI. It generated the same exception. I also downloaded the error data from browser, see attached. 
Does this help? I really depend on this in a project :)

Can i help with the reproduction?

Regards
Endre

**Comment by magyariE** [comment]
[webgme-client-dump (1).json.zip](https://github.com/webgme/webgme/files/7259909/webgme-client-dump.1.json.zip)

**Comment by kecso** [comment]
Thanks for the additional information!
The fact that it happened with child creation is understandable (they too have relations right at the time of creation - towards their bases).
Just one thing. When you mentioned that single add_member resulted in the same error, the project already had large amount of nodes, right?

**Comment by magyariE** [comment]
that's correct. Now I wonder if I shall add some logic to limit the child nodes / node, or we can support of to ~100.000 child nodes per node?

**Comment by kecso** [comment]
I would say, that we should be able to support that (obviously now, it is an issue).
Also, based on the generic organization of projects, I would assume that simply splitting the nodes into multiple containers will not help the situation.

**Comment by magyariE** [comment]
do you have a suggestion or workaround? what would help ? removing from Aspects of the meta node or simplifying the inheritance chain of the meta nodes in question ? How could we work around this limitation?

**Comment by kecso** [comment]
Yes.
In your config, you should be able to increase the limit for overlay sharding.
Set the 'config.core.overlayShardSize' to something huge (like 1000000). That should push back the use and creation of shards (and hopefully give us enough time to fix whatever goes wrong here).

By default, it is 10000, which means that after an overlay store grows over 5000 relations, it starts to shard.

Note that this change will not affect existing shards, and that it is best to only change if 'recreation' of projects is possible (as exporting and importing projects will recreate whatever shard structure is required by the new settings).

Let me know how it goes!

**Comment by kecso** [comment]
Is there any chance that you can share the project where you are able to get the system to fail on the UI?
Also, if sharing is not possible, could you try to export and then import the project back and see what happens?
(I cannot seem to be able to trigger the issue even with having a huge number of relationships)

**Comment by magyariE** [comment]
> Yes. In your config, you should be able to increase the limit for overlay sharding. Set the 'config.core.overlayShardSize' to something huge (like 1000000). That should push back the use and creation of shards (and hopefully give us enough time to fix whatever goes wrong here).
> 
> By default, it is 10000, which means that after an overlay store grows over 5000 relations, it starts to shard.
> 
> Note that this change will not affect existing shards, and that it is best to only change if 'recreation' of projects is possible (as exporting and importing projects will recreate whatever shard structure is required by the new settings).
> 
> Let me know how it goes!

This helped. Thank you very much!!!

**Comment by magyariE** [comment]
> Is there any chance that you can share the project where you are able to get the system to fail on the UI? Also, if sharing is not possible, could you try to export and then import the project back and see what happens? (I cannot seem to be able to trigger the issue even with having a huge number of relationships)

Definitely. I will sanitise the project and send a copy of it.

**Comment by arpika99** [comment]
Hello,

I ran into the same issue. I attached a project and a python plugin, which can reproduce the issue.

The zip contains a python plugin's init file, a test project and a text for instructions.

My opinion is that the set_pointer is limited to 4999, since the error comes up after iteration 4998.

Hope this can help in solving the issue.

Have a nice day.

[webgme_set_pointer_issue.zip](https://github.com/webgme/webgme/files/7553225/webgme_set_pointer_issue.zip)

**Comment by kecso** [comment]
Thanks for the update.
Yes, there is a 10000 limit of storing pointer information (which is essentially the one responsible for sets).
That was my first hunch, but I do not know why the issue have not came up with regular testing...
Maybe there is something special about set member creation that I did not realize earlier.
Anyway, I will make sure to look through your model and check what is going on.

Thanks again
