### ISSUE TITLE
ReadStream was closed while writing file!

### ISSUE THREAD

**Issue by iamfoolberg** [webgme/webgme#1756]
I created a demo docker at https://github.com/iamfoolberg/webgme-docker,
When i import/export project/model, the error is:

```
> ui-components@1.0.0 start
> node app.js

### Running in docker mode ####
2022-08-21T09:56:31.745Z - info: [gme] Node version v16.17.0
2022-08-21T09:56:31.745Z - info: [gme] Logfile [ info ] : /opt/webgme/app/ui-components/server.log
2022-08-21T09:56:31.746Z - info: [gme] Logfile [ error ] : /opt/webgme/app/ui-components/server-error.log
2022-08-21T09:56:31.808Z - info: [gme:server:standalone:middleware:BlobServer:BlobBackend] local-storage: /opt/webgme/app/ui-components/blob-local-storage
2022-08-21T09:56:31.811Z - info: [gme:server:standalone] Valid addresses of gme web server:  http://127.0.0.1:8888  http://10.0.0.145:8888  http://172.18.0.26:8888  http://192.168.110.186:8888
2022-08-21T09:56:31.812Z - info: [gme:server:auth:gmeauth] connecting to: mongodb://mongo:27017/webgme
(node:19) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2022-08-21T09:56:31.836Z - info: [gme:server:standalone:mongo] connecting to: mongodb://mongo:27017/webgme
(node:30) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2022-08-21T09:56:32.070Z - info: [gme:server:standalone] Server is listening ...
2022-08-21T09:56:40.645Z - error: [gme:server:standalone:middleware:BlobServer:BlobBackend] readStream on close
2022-08-21T09:56:40.646Z - error: [gme:server:standalone:middleware:BlobServer] Error: ReadStream was closed while writing file!
2022-08-21T09:56:40.649Z - error: [gme:server:worker:simpleworker:pid_30:WorkerFunctions] exportProjectToFile failed with error
{
  message: 'Internal Server Error',
  stack: 'Error: Internal Server Error\n' +
    '    at Request.callback (/opt/webgme/app/ui-components/node_modules/superagent/lib/node/index.js:706:15)\n' +
    '    at IncomingMessage.<anonymous> (/opt/webgme/app/ui-components/node_modules/superagent/lib/node/index.js:916:18)\n' +
    '    at IncomingMessage.emit (node:events:525:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  status: 500,
  response: {
    _events: {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: {
      _readableState: [Object],
      _events: [Object],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [Object],
      _consuming: false,
      _dumped: false,
      req: [Object],
      text: 'ReadStream was closed while writing file!'
    },
    request: {
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      _agent: [Object],
      _formData: null,
      method: 'POST',
      url: 'http://127.0.0.1:8888/rest/blob/createFile/project.json',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [Object],
      _redirectList: [],
      _streamRequest: false,
      _data: '{"rootHash":"#2a9c886ce9fa7cba5719174e9b1c4526a5111544","projectId":"guest+test","kind":"EmptyProject","branchName":"master","commitHash":"#2ce7fca89d09082a95a889872a2e8b64eca71a07","hashes":{"objects":["#2a9c886ce9fa7cba5719174e9b1c4526a5111544","#3d492d4d64255512d17babfea6e8e1b204142265","#2bf3b17aefda8b7623d78ba264004dda996adb9e","#86b487eead46adf398da1c9887f10ea21f571942"],"assets":[]},"objects":[{"1":"#3d492d4d64255512d17babfea6e8e1b204142265","_id":"#2a9c886ce9fa7cba5719174e9b1c4526a5111544","_nullptr":{"atr":{"name":"_null_pointer"}},"ovr":{"":{"base":"/_nullptr"},"/_sets/MetaAspectSet/1133782405":{"member":"/1"},"/_sets/MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d/125899614":{"member":"/1"},"/_meta/children/_sets/items/302362349":{"member":"/1"},"/K":{"base":"/1"},"/_sets/MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d/xk44jE":{"member":"/K"},"/_sets/MetaAspectSet/fk8IYd":{"member":"/K"},"/C":{"base":"/K"}},"atr":{"_relguid":"03d360729e097866cb4ed0a36ff825f6","name":"ROOT"},"reg":{"MetaSheets":[{"SetID":"MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d","order":0,"title":"META"}],"ProjectRegistry":{"FCO_ID":"/1"},"_sets_":17},"_sets":{"MetaAspectSet":{"1133782405":{"reg":{"_":"_","position":{"x":100,"y":100}}},"reg":{"_":"_"},"fk8IYd":{"reg":{"_":"_","position":{"x":77,"y":271}}}},"_nullptr":{"atr":{"name":"_null_pointer"}},"ovr":{"":{"MetaAspectSet":"/_nullptr","MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d":"/_nullptr"}},"MetaAspectSet_68f8146d-b1b7-6c40-3464-f8c070e97e8d":{"125899614":{"reg":{"_":"_","position":{"x":346,"y":19}}},"reg":{"_":"_"},"xk44jE":{"reg":{"_":"_","position":{"x":228,"y":211}}}}},"_meta":{"atr":{"name":{"type":"string"}},"children":{"_sets":{"items":{"302362349":{"reg":{"_":"_"},"atr":{"min":-1,"max":-1}},"reg":{"_":"_"}},"_nullptr":{"atr":{"name":"_null_pointer"}},"ovr":{"":{"items":"/_nullptr"}}},"reg":{"_sets_":4}}},"__v":"1.2.0","K":"#2bf3b17aefda8b7623d78ba264004dda996adb9e","C":"#86b487eead46adf398da1c9887f10ea21f571942"},{"_id":"#3d492d4d64255512d17babfea6e8e1b204142265","_nullptr":{"atr":{"name":"_null_pointer"}},"ovr":{"":{"base":"/_nullptr"}},"atr":{"_relguid":"de5a7e097ce3914f3d834f0c20e7e5b3","name":"FCO"},"reg":{"DisplayFormat":"$name","position":{"x":100,"y":58},"isAbstract":true},"_meta":{"atr":{"name":{"type":"string"}}},"__v":"1.2.0"},{"_id":"#2bf3b17aefda8b7623d78ba264004dda996adb9e","atr":{"_relguid":"978e91b69f65f1a5c84acb4fb4f353d6","name":"FCO_instance"},"reg":{"position":{"x":272,"y":45},"decorator":"MultilineAttributeDecorator","decoratorWidth":170,"decoratorHeight":80,"isAbstract":false},"__v":"1.2.0"},{"_id":"#86b487eead46adf398da1c9887f10ea21f571942","atr":{"_relguid":"fc628bb61cb5c0b29958b6504def0d18"},"reg":{"position":{"x":120,"y":321}},"__v":"1.2.0"}]}',
      req: [Object],
      protocol: 'http:',
      host: '127.0.0.1:8888',
      _endCalled: true,
      _callback: [Function (anonymous)],
      res: [Object],
      response: [Object],
      called: true
    },
    req: { '$ref': '$["response"]["res"]["req"]' },
    text: 'ReadStream was closed while writing file!',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      'x-powered-by': 'Express',
      vary: 'X-HTTP-Method-Override, Accept-Encoding',
      'content-type': 'text/html; charset=utf-8',
      'content-length': '41',
      etag: 'W/"29-wAT+M/ei9pYSiJGgb9mvcHI+MmE"',
      date: 'Sun, 21 Aug 2022 09:56:40 GMT',
      connection: 'keep-alive',
      'keep-alive': 'timeout=5'
    },
    header: { '$ref': '$["response"]["headers"]' },
    statusCode: 500,
    status: 500,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: {
      status: 500,
      text: 'ReadStream was closed while writing file!',
      method: 'POST',
      path: '/rest/blob/createFile/project.json'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: 'text/html',
    charset: 'utf-8',
    links: {},
    setEncoding: [Function: bound ],
    redirects: { '$ref': '$["response"]["request"]["_redirectList"]' }
  }
}
(node:37) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

```
Did i miss something?

**Comment by iamfoolberg** [comment]
the docker swarm stack file:
```
version: '3.1'
services:
  mongo:
    networks:
      mydockernet:
        aliases:
          - mongo
    dns: 192.168.2.1
    image: mongo:4.2.7-bionic
    ports:
      - 27017:27017
#    environment:
#      - DB_TYPE:"mysql"
    volumes:
      - mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == infra
      restart_policy:
        condition: on-failure

  webgme:
    networks:
      mydockernet:
        aliases:
          - etherpad
    dns: 192.168.2.1
    image: berg/webgme:20220821
    ports:
      - 8888:8888
#    environment:
#      - DB_TYPE:"mysql"
    volumes:
      - webgme:/opt/webgme
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == common
      restart_policy:
        condition: on-failure
volumes:
  mongo:
  webgme:
networks:
  mydockernet:
    external: true

```

And the config.docker.js looks like

```
var config = require('./config.default');
console.info('### Running in docker mode ####');
module.exports = config;

//config your mongo db url
config.mongo.uri = 'mongodb://mongo:27017/webgme';

//do not change this port, map it in your docker container.
config.server.port=8888;
```
