### ISSUE TITLE
Downloading CyPhyLight crashes WebGME

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#34]
WebGME version webgme@0.5.6

Using the mongo at zsolt-ws.isis.vanderbilt.edu (maybe Zsolt can give you a copy of the data files, or you can connect to it)

Trying to "Export Project... " CyPhyLight, i.e. GETing
http://localhost:8888/rest/etf?project=CyPhyLight&root=%238282dcbc609c855a1c0eb204820a862370450666&path=&output=CyPhyLight_master

Results in this stack:

    C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\util\assert.js:17
                            throw error;
                                  ^
    Error: ASSERT failed
        at assert (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\util\assert.js:12:16)
        at Object.core.getAttribute (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\coretype.js:257:4)
        at Object._core.getMiddleGuid (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\guidcore.js:87:51)
        at Object._core.getGuid (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\guidcore.js:94:32)
        at UnwrapListener.callback (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\coreclient\tojson.js:320:65)
        at UnwrapListener.onResolved (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:502:8)
        at Future.resolve (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:51:17)
        at tasync_trace_start [as onResolved] (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:379:9)
        at Future.resolve (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:51:17)
        at tasync_trace_start [as onResolved] (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:379:9)
        at Future.resolve (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:51:17)
        at tasync_trace_start [as onResolved] (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:379:9)
        at Future.resolve (C:\Users\kevin\Documents\webgme-domain-tools\node_modules\webgme\core\tasync.js:51:17)

**Comment by ksmyth** [comment]
Apparently, this has been fixed.
