### ISSUE TITLE
Export branch fails

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#387]
When I want to export the attached project, it throws an error: "ASSERT failed." and after a while the server crashes. Also, when I'm working on the project, time to time, it throws the same or similar error and I restart the server to continue working.

I have no idea what causes this issue. There might be some problem with the project but even if that's the case the UI shouldn't have allowed to make such changes.

Database collection exported with **mongoexport**:
https://drive.google.com/file/d/0B6icounl9q69VGRUZWVMekJZeXM/view?usp=sharing

```
Throwing Error: ASSERT failed
    at assert (/home/hakan/github/webgme/webgme/src/common/util/assert.js:14:25)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:186:17)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)
    at __ageRoots (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:199:17)
    at Object.getChild (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:364:13)

2015-06-09T21:47:03.068Z - error: uncaughtException: ASSERT failed 
{ date: 'Tue Jun 09 2015 16:47:03 GMT-0500 (CDT)',
  process: 
   { pid: 31443,
     uid: 1000,
     gid: 1000,
     cwd: '/home/hakan/github/webgme/webgme',
     execPath: '/usr/bin/nodejs',
     version: 'v0.10.25',
     argv: 
      [ '/usr/bin/nodejs',
        '/home/hakan/github/webgme/webgme/src/server/worker/simpleworker.js' ],
     memoryUsage: 
      { rss: 72945664,
        heapTotal: 62420840,
        heapUsed: 39869648 } },
  os: 
   { loadavg: 
      [ 1.0458984375,
        0.63623046875,
        0.5458984375 ],
     uptime: 348473.327395846 },
  trace: 
   [ { column: 25,
       file: '/home/hakan/github/webgme/webgme/src/common/util/assert.js',
       function: 'assert',
       line: 14,
       method: null,
       native: false },
     { column: 17,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 186,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 21,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageNodes',
       line: 191,
       method: null,
       native: false },
     { column: 17,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: '__ageRoots',
       line: 199,
       method: null,
       native: false },
     { column: 13,
       file: '/home/hakan/github/webgme/webgme/src/common/core/coretree.js',
       function: 'Object.getChild',
       line: 364,
       method: 'getChild',
       native: false } ],
  stack: 
   [ 'Error: ASSERT failed',
     '    at assert (/home/hakan/github/webgme/webgme/src/common/util/assert.js:14:25)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:186:17)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageNodes (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:191:21)',
     '    at __ageRoots (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:199:17)',
     '    at Object.getChild (/home/hakan/github/webgme/webgme/src/common/core/coretree.js:364:13)' ] }
2015-06-09T21:49:02.910Z - error: uncaughtException: channel closed 
{ date: 'Tue Jun 09 2015 16:49:02 GMT-0500 (CDT)',
  process: 
   { pid: 31437,
     uid: 1000,
     gid: 1000,
     cwd: '/home/hakan/github/webgme/webgme',
     execPath: '/usr/bin/nodejs',
     version: 'v0.10.25',
     argv: 
      [ 'node',
        '/home/hakan/github/webgme/webgme/src/bin/start_server.js' ],
     memoryUsage: 
      { rss: 133206016,
        heapTotal: 108770960,
        heapUsed: 73271152 } },
  os: 
   { loadavg: 
      [ 0.25,
        0.46728515625,
        0.49267578125 ],
     uptime: 348593.163181883 },
  trace: 
   [ { column: 26,
       file: 'child_process.js',
       function: 'ChildProcess.target.send',
       line: 402,
       method: 'target.send',
       native: false },
     { column: 31,
       file: '/home/hakan/github/webgme/webgme/src/server/worker/serverworkermanager.js',
       function: 'Object.result',
       line: 207,
       method: 'result',
       native: false },
     { column: 39,
       file: '/home/hakan/github/webgme/webgme/src/server/storage/server.js',
       function: 'stop',
       line: 815,
       method: null,
       native: false },
     { column: 17,
       file: '/home/hakan/github/webgme/webgme/src/server/storage/server.js',
       function: 'stopConnectedWorkers',
       line: 824,
       method: null,
       native: false },
     { column: 17,
       file: '/home/hakan/github/webgme/webgme/src/server/storage/server.js',
       function: '',
       line: 742,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Socket.EventEmitter.emit',
       line: 95,
       method: 'EventEmitter.emit',
       native: false },
     { column: 10,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/socket.js',
       function: 'Socket.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 8,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/socket.js',
       function: 'Socket.onclose',
       line: 418,
       method: 'onclose',
       native: false },
     { column: 12,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/client.js',
       function: 'Client.onclose',
       line: 230,
       method: 'onclose',
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Socket.EventEmitter.emit',
       line: 117,
       method: 'EventEmitter.emit',
       native: false },
     { column: 10,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/lib/socket.js',
       function: 'Socket.onClose',
       line: 248,
       method: 'onClose',
       native: false },
     { column: 16,
       file: 'events.js',
       function: 'WebSocket.g',
       line: 180,
       method: 'g',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'WebSocket.EventEmitter.emit',
       line: 92,
       method: 'EventEmitter.emit',
       native: false },
     { column: 8,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/lib/transport.js',
       function: 'WebSocket.Transport.onClose',
       line: 113,
       method: 'Transport.onClose',
       native: false },
     { column: 16,
       file: 'events.js',
       function: 'WebSocket.g',
       line: 180,
       method: 'g',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'WebSocket.EventEmitter.emit',
       line: 98,
       method: 'EventEmitter.emit',
       native: false },
     { column: 10,
       file: '/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js',
       function: 'WebSocket.cleanupWebsocketResources',
       line: 905,
       method: 'cleanupWebsocketResources',
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Socket.EventEmitter.emit',
       line: 117,
       method: 'EventEmitter.emit',
       native: false },
     { column: 16,
       file: '_stream_readable.js',
       function: null,
       line: 920,
       method: null,
       native: false },
     { column: 13,
       file: 'node.js',
       function: 'process._tickCallback',
       line: 415,
       method: '_tickCallback',
       native: false } ],
  stack: 
   [ 'Error: channel closed',
     '  at ChildProcess.target.send (child_process.js:402:26)',
     '  at Object.result (/home/hakan/github/webgme/webgme/src/server/worker/serverworkermanager.js:207:31)',
     '  at stop (/home/hakan/github/webgme/webgme/src/server/storage/server.js:815:39)',
     '  at stopConnectedWorkers (/home/hakan/github/webgme/webgme/src/server/storage/server.js:824:17)',
     '  at Socket.<anonymous> (/home/hakan/github/webgme/webgme/src/server/storage/server.js:742:17)',
     '  at Socket.EventEmitter.emit (events.js:95:17)',
     '  at Socket.emit (/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/socket.js:129:10)',
     '  at Socket.onclose (/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/socket.js:418:8)',
     '  at Client.onclose (/home/hakan/github/webgme/webgme/node_modules/socket.io/lib/client.js:230:12)',
     '  at Socket.EventEmitter.emit (events.js:117:20)',
     '  at Socket.onClose (/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/lib/socket.js:248:10)',
     '  at WebSocket.g (events.js:180:16)',
     '  at WebSocket.EventEmitter.emit (events.js:92:17)',
     '  at WebSocket.Transport.onClose (/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/lib/transport.js:113:8)',
     '  at WebSocket.g (events.js:180:16)',
     '  at WebSocket.EventEmitter.emit (events.js:98:17)',
     '  at WebSocket.cleanupWebsocketResources (/home/hakan/github/webgme/webgme/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:905:10)',
     '  at Socket.EventEmitter.emit (events.js:117:20)',
     '  at _stream_readable.js:920:16',
     '  at process._tickCallback (node.js:415:13)',
     '' ] }
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by pmeijer** [comment]
Hakan, the workaround for now is to increase the MAX_AGE in src/common/core/coretree.js. I've talked to Tamas and he suspects that the increase of the node.ages are due to some nodes being referenced when they shouldn't.
