### ISSUE TITLE
Export branch fails

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#411]
Project: https://drive.google.com/file/d/0B6icounl9q69VDVLNTVVWDhfcmc/view?usp=sharing

Server:
```
Wrong node Error: isobject
    at __test (/home/hakan/github/webgme/webgme/src/common/core/corerel.js:34:19)
    at Object.isValidNode (/home/hakan/github/webgme/webgme/src/common/core/corerel.js:53:17)
    at isValidNode (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:38:40)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
Wrong node Error: core
    at __test (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:32:23)
    at isValidNode (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:38:17)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
    at tasync_trace_start [as onResolved] (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:366:35)
Throwing Error: ASSERT failed
    at assert (/home/hakan/github/webgme/webgme/src/common/util/assert.js:14:25)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:13)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
    at tasync_trace_start [as onResolved] (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:366:35)
    at Future.resolve (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:53:26)
....
```
Full server side error: https://drive.google.com/file/d/0B6icounl9q69Vi13QVVLX1VRMGM/view?usp=sharing

Client:
url:
```
http://localhost:8888/worker/simpleResult/9954a2b1-90b0-9d9a-ce51-a4930419c263/a27_np_master
```
page:
```
Internal Server Error
```
console:
```
GET http://localhost:8888/favicon.ico 404 (Not Found)
```

**Comment by kecso** [comment]
could you provide a mongodump from the given project?
thanks

**Comment by hakantunc** [comment]
https://drive.google.com/file/d/0B6icounl9q69VDVLNTVVWDhfcmc/view?usp=sharing

**Comment by pmeijer** [comment]
Is this issue related to Kevins issue?
`Wrong node Error: isobject
    at __test (http://editor.dev.webgme.org/common/core/corerel.js:34:19)
    at Object.isValidNode (http://editor.dev.webgme.org/common/core/corerel.js:53:17)
    at isValidNode (http://editor.dev.webgme.org/common/core/coretype.js:38:40)
    at Object.core.getBase (http://editor.dev.webgme.org/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenPaths (http://editor.dev.webgme.org/common/core/coretype.js:759:31)
    at loadChildrenPattern (http://editor.dev.webgme.org/js/client.js:1112:38)
    at childLoaded (http://editor.dev.webgme.org/js/client.js:1125:25)
    at Object.func.tasync_unwraped [as loadChild] (http://editor.dev.webgme.org/common/core/tasync.js:534:21)
coretype.js:42 Wrong node Error: core
    at __test (http://editor.dev.webgme.org/common/core/coretype.js:32:23)
    at isValidNode (http://editor.dev.webgme.org/common/core/coretype.js:38:17)
    at Object.core.getBase (http://editor.dev.webgme.org/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenPaths (http://editor.dev.webgme.org/common/core/coretype.js:759:31)
    at loadChildrenPattern (http://editor.dev.webgme.org/js/client.js:1112:38)
    at childLoaded (http://editor.dev.webgme.org/js/client.js:1125:25)
    at Object.func.tasync_unwraped [as loadChild] (http://editor.dev.webgme.org/common/core/tasync.js:534:21)
    at loadChildrenPattern (http://editor.dev.webgme.org/js/client.js:1148:34)
assert.js:17 Throwing Error: ASSERT failed
    at assert (http://editor.dev.webgme.org/common/util/assert.js:14:25)
    at Object.core.getBase (http://editor.dev.webgme.org/common/core/coretype.js:60:13)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (http://editor.dev.webgme.org/common/core/coretype.js:195:87)
    at Object.core.getChildrenPaths (http://editor.dev.webgme.org/common/core/coretype.js:759:31)
    at loadChildrenPattern (http://editor.dev.webgme.org/js/client.js:1112:38)
    at childLoaded (http://editor.dev.webgme.org/js/client.js:1125:25)
    at Object.func.tasync_unwraped [as loadChild] (http://editor.dev.webgme.org/common/core/tasync.js:534:21)
    at loadChildrenPattern (http://editor.dev.webgme.org/js/client.js:1148:34)
    at childLoaded (http://editor.dev.webgme.org/js/client.js:1125:25)`

**Comment by kecso** [comment]
I believe they are coming from the same source, but until we have not figured it out we cannot be sure.

**Comment by pmeijer** [comment]
OK, I would ask Zsolt for the json he's trying to import and try it out on an older version of webgme before the storage changed.

**Comment by lattmann** [comment]
You can export the project from here:
http://editor.dev.webgme.org/?project=Template_module&branch=master&node=root&aspect=All&selection=%2F1922727130
