### ISSUE TITLE
Corediff sometimes gets invalid path for pointer target

### ISSUE THREAD

**Issue by lattmann** [webgme/webgme#458]
Stack trace:

```
Trace: { base: '/1008889918/1993805430' }
    at Object.core.loadByPath (./node_modules/webgme/src/common/core/coretype.js:122:25)
    at setPointer (./node_modules/webgme/src/common/core/corediff.js:946:36)
    at applyPointerChanges (./node_modules/webgme/src/common/core/corediff.js:963:28)
    at Function.<anonymous> (./node_modules/webgme/src/common/core/corediff.js:895:24)
    at Object.call (./node_modules/webgme/src/common/core/tasync.js:405:30)
    at applyNodeChange (./node_modules/webgme/src/common/core/corediff.js:885:27)
    at ./node_modules/webgme/src/common/core/corediff.js:905:46
    at tasync_trace_start [as onResolved] (./node_modules/webgme/src/common/core/tasync.js:366:35)
    at Future.resolve (./node_modules/webgme/src/common/core/tasync.js:53:26)
    at tasync_trace_start [as onResolved] (./node_modules/webgme/src/common/core/tasync.js:382:18)
    at Future.resolve (./node_modules/webgme/src/common/core/tasync.js:53:26)
    at tasync_trace_start [as onResolved] (./node_modules/webgme/src/common/core/tasync.js:382:18)
    at Future.resolve (./node_modules/webgme/src/common/core/tasync.js:53:26)
    at tasync_trace_start [as onResolved] (./node_modules/webgme/src/common/core/tasync.js:382:18)
    at Future.resolve (./node_modules/webgme/src/common/core/tasync.js:53:26)
    at args.(anonymous function) (./node_modules/webgme/src/common/core/tasync.js:472:32)
    at ./node_modules/webgme/src/common/storage/project/cache.js:61:37
    at ./node_modules/q/q.js:2027:17
    at runSingle (./node_modules/q/q.js:137:13)
    at flush (./node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by kecso** [comment]
Cannot reproduce the issue.
All base pointer change scenarios were evaluated and no such error found.
