### ISSUE TITLE
Uncaught Error while loading a branch

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#632]
When trying to load branch **exp_13**, the footbar shows **pulling[1]** and the browser logs the following error. Webgme doesn't load the branch. There's no log on the server side.

The mongodump of the project is here: https://drive.google.com/file/d/0B6icounl9q69NXNTUEN3ZGZjM3c/view?usp=sharing

````
Throwing Error: ASSERT failed
    at assert (http://localhost:8888/common/util/assert.js:14:25)
    at cacheInsert (http://localhost:8888/common/storage/project/cache.js:26:13)
    at Object.cb (http://localhost:8888/common/storage/project/cache.js:68:41)
    at http://localhost:8888/common/storage/storageclasses/objectloaders.js:92:38
    at Socket.<anonymous> (http://localhost:8888/common/storage/socketio/websocket.js:32:30)
    at Socket.5.Socket.onack (http://localhost:8888/socket.io/socket.io.js:920:6)
    at Socket.5.Socket.onpacket (http://localhost:8888/socket.io/socket.io.js:845:12)
    at Manager.8.module.exports (http://localhost:8888/socket.io/socket.io.js:1197:15)
    at Manager.9.Emitter.emit (http://localhost:8888/socket.io/socket.io.js:1335:20)
    at Manager.3.Manager.ondecoded (http://localhost:8888/socket.io/socket.io.js:395:8)
assert.js:14 Uncaught Error: ASSERT failed
Uncaught Error: ASSERT failedassert @ assert.js:14cacheInsert @ cache.js:26(anonymous function) @ cache.js:68(anonymous function) @ objectloaders.js:92(anonymous function) @ websocket.js:325.Socket.onack @ socket.io.js:9205.Socket.onpacket @ socket.io.js:8458.module.exports @ socket.io.js:11979.Emitter.emit @ socket.io.js:13353.Manager.ondecoded @ socket.io.js:3958.module.exports @ socket.io.js:11979.Emitter.emit @ socket.io.js:133544.Decoder.add @ socket.io.js:58823.Manager.ondata @ socket.io.js:3858.module.exports @ socket.io.js:11979.Emitter.emit @ socket.io.js:133513.Socket.onPacket @ socket.io.js:1953(anonymous function) @ socket.io.js:17719.Emitter.emit @ socket.io.js:133514.Transport.onPacket @ socket.io.js:237814.Transport.onData @ socket.io.js:237019.WS.addEventListeners.ws.onmessage @ socket.io.js:3433
````

**Comment by kecso** [comment]
Could you please check your webgme version?
I've tried with the current master and it loaded without any issue.

Thanks,
Tamas

**Comment by hakantunc** [comment]
1.1.0-beta.1
commit 4cbc6c1b0df3a518101016168f26da4d471d62a0

I tried again, and it's the same.

**Comment by lattmann** [comment]
Clear browser's cache and make sure you get the latest socket.io, unfortunately we went back on socket.io version, and it does not contain the bug fix for the Socket.5.Socket.onack issue, and this seems to me that issue:
https://github.com/lattmann/socket.io-client/commit/bb0baf236414e05a3548c1003b3a5f13a8042188

If you ran older versions of webgme, maybe socket.io client version 1.3.6-something is cached. Now we are using https://github.com/webgme/webgme/blame/master/package.json#L57-L58

**Comment by hakantunc** [comment]
Thanks
