### ISSUE TITLE
Uncaught exception when switching between projects.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#664]
Throwing Error: ARPath.calculateStartEndPorts: port BOX_000261__N has invalid this.owner!
    at assert (http://localhost:8888/common/util/assert.js:14:25)
    at AutoRouterPath.calculateStartPorts (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Path.js:129:13)
    at AutoRouterPath.calculateStartEndPorts (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Path.js:112:27)
    at AutoRouterGraph._quickConnectDisconnectedPaths (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Graph.js:1990:22)
    at AutoRouterGraph.routeAsync (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Graph.js:1970:33)
    at AutoRouter.routeAsync (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.js:464:20)
    at AutoRouterActionApplier._invokeAutoRouterMethodUnsafe (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.ActionApplier.js:159:43)
    at AutoRouterWorker._handleMessage (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Worker.js:88:61)
    at AutoRouterWorker.handleMessage (http://localhost:8888/js/Widgets/DiagramDesigner/AutoRouter.Worker.js:70:18)

**Comment by brollb** [comment]
Don't know how to replicate this

**Comment by pmeijer** [comment]
"Don't know how to replicate this"
