### ISSUE TITLE
Project import fails with exception.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#856]
```
Throwing Error: ASSERT failed
    at assert (C:\GIT\webgme\src\common\util\assert.js:14:25)
    at CoreQ.getBase (C:\GIT\webgme\src\common\core\coretype.js:794:13)
    at updateInheritance (C:\GIT\webgme\src\common\core\users\serialization.js:994:29)
    at C:\GIT\webgme\src\common\core\users\serialization.js:1392:21
    at loadImportBases (C:\GIT\webgme\src\common\core\users\serialization.js:887:17)
    at C:\GIT\webgme\src\common\core\users\serialization.js:1336:17
    at C:\GIT\webgme\src\common\core\users\serialization.js:823:13
    at C:\GIT\webgme\node_modules\q\q.js:2027:17
    at runSingle (C:\GIT\webgme\node_modules\q\q.js:137:13)
    at flush (C:\GIT\webgme\node_modules\q\q.js:125:13)

2016-02-25T16:58:18.194Z - error: uncaughtException: ASSERT failed
{ date: 'Thu Feb 25 2016 10:58:18 GMT-0600 (Central Standard Time)',
  process:
   { pid: 10160,
     uid: null,
     gid: null,
     cwd: 'C:\\GIT\\webgme',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\GIT\\webgme\\src\\server\\worker\\simpleworker.js' ],
     memoryUsage: { rss: 102354944, heapTotal: 88684032, heapUsed: 57776952 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 1131647.3574798 },
  trace:
   [ { column: 25,
       file: 'C:\\GIT\\webgme\\src\\common\\util\\assert.js',
       function: 'assert',
       line: 14,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\coretype.js',
       function: 'CoreQ.getBase',
       line: 794,
       method: 'getBase',
       native: false },
     { column: 29,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: 'updateInheritance',
       line: 994,
       method: null,
       native: false },
     { column: 21,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 1392,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: 'loadImportBases',
       line: 887,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 1336,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 823,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: null,
       line: 2027,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: 'runSingle',
       line: 137,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: 'flush',
       line: 125,
       method: null,
       native: false } ],
  stack:
   [ 'Error: ASSERT failed',
     '    at assert (C:\\GIT\\webgme\\src\\common\\util\\assert.js:14:25)',
     '    at CoreQ.getBase (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:794:13)',
     '    at updateInheritance (C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:994:29)',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:1392:21',
     '    at loadImportBases (C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:887:17)',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:1336:17',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:823:13',
     '    at C:\\GIT\\webgme\\node_modules\\q\\q.js:2027:17',
     '    at runSingle (C:\\GIT\\webgme\\node_modules\\q\\q.js:137:13)',
     '    at flush (C:\\GIT\\webgme\\node_modules\\q\\q.js:125:13)' ] }
```

**Comment by pmeijer** [comment]
Attached is project.json
[nag_fail.txt](https://github.com/webgme/webgme/files/146969/nag_fail.txt)
