### ISSUE TITLE
Exporting branch + importing into project works, but using the Export Import and Update Library plugin fails

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#949]
For the project attached (which was created using `export branch`), I get the following error when running the export library plugin:

```
2016-04-14T17:04:26.116Z - error: [gme:server:worker:simpleworker:pid_15982:WorkerFunctions] plugin [ExportImport] failed with error Error: [/p/1/U/0] has a colliding guid {b2357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/1] has a colliding guid {b9357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/3] has a colliding guid {fe357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/4] has a colliding guid {93357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/6] has a colliding guid {fc357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/8] has a colliding guid {91357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/X] has a colliding guid {b0357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/Y] has a colliding guid {bb357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/M] has a colliding guid {40357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/N] has a colliding guid {42357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/g] has a colliding guid {49357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/c] has a colliding guid {4b357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/l] has a colliding guid {61357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/a] has a colliding guid {63357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/0D] has a colliding guid {68357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/x] has a colliding guid {6a357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/t] has a colliding guid {05357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/o] has a colliding guid {07357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/S] has a colliding guid {0c357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/d] has a colliding guid {0e357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/QQ] has a colliding guid {24357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/A] has a colliding guid {26357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/aH] has a colliding guid {2d357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/z] has a colliding guid {2f357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/L] has a colliding guid {d4357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/q] has a colliding guid {d6357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/R] has a colliding guid {dd357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/k] has a colliding guid {df357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/E] has a colliding guid {f5357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/I] has a colliding guid {f7357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/b] has a colliding guid {98357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!
[/p/1/U/F] has a colliding guid {9a357525-43a6-9058-d9f6-607e9275fb5e} and will be skipped!

    at finish (/home/jeb/Repositories/webgme-rosmod/node_modules/webgme/src/server/worker/workerrequests.js:327:56)
    at /home/jeb/Repositories/webgme-rosmod/node_modules/webgme/src/plugin/nodemanagerbase.js:177:17
    at /home/jeb/Repositories/webgme-rosmod/node_modules/webgme/src/plugin/coreplugins/ExportImport/ExportImport.js:98:17
    at finalProcesses (/home/jeb/Repositories/webgme-rosmod/node_modules/webgme/src/common/core/users/serialization.js:457:13)
    at null.<anonymous> (/home/jeb/Repositories/webgme-rosmod/node_modules/webgme/src/common/core/users/serialization.js:469:21)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

[ROSMOD+Samples_master.zip](https://github.com/webgme/webgme/files/219588/ROSMOD.Samples_master.zip)

**Comment by finger563** [comment]
Note: this project is in some weird error state; despite the fact that a `Node` can contain a `Component`, I'm not allowed to create a `Component` inside of a `Node`.  I think this is a result of the branch export.  I used branch export because the exporter plugin failed.  I think the exporter plugin failed because of the different aspects I have in my `meta` and the fact that some objects are in multiple aspects.

**Comment by pmeijer** [comment]
The Export-Import plugin uses the old serialization (both for export and import).
To import a webgmex-file, use the 'Import' option in Create Project Dialog.

**Comment by pmeijer** [comment]
This issue was for the old model import/export.
